name: Release on tag creation push
on:
  push:
    tags:
      - 'v*'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Build release
        run: jar cf Dossier-Facile-Keycloak-${{github.ref_name}}.jar *
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false