name: Release on tag creation push
on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: jar cf Dossier-Facile-Keycloak-${{github.ref_name}}.jar LICENSE META-INF theme
#      - run: ${{ github.repository }}
#      - run: echo '${{ github.repository.releases_url }}'
#      - run: export release_url_tagged =$(echo ${{ github.repository.releases_url}} | sed -E 's/\{\/id\}/\?tag=${{github.ref_name}}/g )'
#      - run: echo $release_url_tagged
#      - run: echo '${{ github.repository.releases_url }}'
#      - run: echo https://api.github.com/repos/fabiengo/Dossier-Facile-Keycloak/releases?tag=4.88
      - run: echo ${{ github.event.release.upload_url }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Dossier-Facile-Keycloak-${{github.ref_name}}.jar
          asset_name: Dossier-Facile-Keycloak-${{github.ref_name}}.jar
          asset_content_type: application/zip